" 戒め
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>

" setting
set fenc=utf-8
set nobackup
set noswapfile
set autoread
set hidden
set showcmd

" visual setting
syntax enable
set number
set cursorline
set cursorcolumn
set virtualedit=onemore
set autoindent
set smartindent
set showmatch
set laststatus=2
set expandtab
set tabstop=2
set shiftwidth=2
set ambiwidth=double

" search option
set ignorecase
set smartcase
set incsearch
set hlsearch
nmap <Esc><Esc> :nohlsearch<CR><Esc>

" other setting
set backspace=indent,eol,start
set showmatch
set wildmenu
set history=5000

" enable mouse
if has('mouse')
  set mouse=a
  if has('mouse_sgr')
    set ttymouse=sgr
  elseif v:version > 703 || v:version is 703 && has('patch632')
    set ttymouse=sgr
  else
    set ttymouse=xterm2
  endif
endif

""""""""""""""""""""
""" 以下 NeoBundle
""""""""""""""""""""

if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim/

  if !isdirectory(expand("~/.vim/bundle/neobundle.vim/"))
    echo "install NeoBundle..."
    :call system("git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim")
  endif
endif

call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'
"----------------------------------------------------------
NeoBundle 'bronson/vim-trailing-whitespace'
NeoBundle 'Yggdroot/indentLine'
"----------------------------------------------------------
call neobundle#end()

filetype plugin indent on

NeoBundleCheck
